### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by sebabouche** [SeeLog/python-init-generator#1]
Awesome plugin ;-) but unfortunately, it doesn't work on my end.

![Screenshot](https://user-images.githubusercontent.com/6465147/71853052-963ff880-30da-11ea-898e-925b96abe830.jpg)

#### VSCode version
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

**Comment by pvemulapalli** [comment]
I also have the same issue

**Comment by bahamut45** [comment]
+1

**Comment by kgrvamsi** [comment]
+1

**Comment by robbiemu** [comment]
getting a better error message, but same basic problem:
```
Command 'Python init Generator: Generate __init__.py' resulted in an error (command 'extension.generateInit' not found)
```

it it as if the extension activate method is not called

**Comment by Maximellerbach** [comment]
![image](https://user-images.githubusercontent.com/38923282/90439700-44326d00-e0d6-11ea-80c2-4a0615a74c97.png)
same error on my side :)

**Comment by cocojim** [comment]
i have the same error on my side. 
Command 'Python init Generator: Generate __init__.py' resulted in an error (command 'extension.generateInit' not found)

**Comment by estyxx** [comment]
I have made a fix for this   #3 , hope the maintainer @SeeLog  can have a look soon :) Will be nice to use this extension!

**Comment by SeeLog** [comment]
Now, merged #3 and publish this extension. But it still seemed to be occurred this problem.

**Comment by SeeLog** [comment]
When debugging, this extension works fine.
But compile and install this extension or install from Market, same issue is occurred.

Does anyone have any idea to solve this problem?

**Comment by robbiemu** [comment]
sometimes its nice to find someone else with a similar problem, even if it is not your own: https://github.com/microsoft/vscode/issues/23300

when I download, npm i, and then vsce ls in your repo, I see your node_modules ... but I'm not sure they are in your package. in general, everything looks right now (albeit with old typescript -- I'll submit a pr just to freshen style a bit)

**Comment by SeeLog** [comment]
Finally, I might fixed this problem!
The problem was `glob` package is not included in dependencies.
I have fixed it, also have published!

Try it:
https://marketplace.visualstudio.com/items?itemName=SeeLog.python-init-generator

I test this extension on MacOS and It works.

**Comment by SeeLog** [comment]
I'll close this issue when someone else can confirm it works.

**Comment by robbiemu** [comment]
I uninstalled and restarted vscode, then installed 0.0.9 from the extensions tab, and found it is now working (however, it was also working when I locally installed the version I submitted in my PR)

**Comment by SeeLog** [comment]
Thank you for your cooperation!
Now, close this issue.
