### ISSUE TITLE
Extension does not include node_modules

### ISSUE THREAD

**Issue by sisoe24** [SeeLog/python-init-generator#12]
I was trying to generate the __init__.py from the context menu when I realized it wasn't working since the extension gets activated only after the main command is executed. 
I then ran the main command, but it failed to run. So I noticed that the extension only works in the development environment but fails to get activated outside.

After some inspection. I've found this in the Output window under Extension Host the following error:

```
Activating extension SeeLog.python-init-generator failed due to an error:
2023-01-13 12:12:00.853 [error] Error: Cannot find module 'glob'
Require stack:
- /Users/virgil/.vscode/extensions/seelog.python-init-generator-0.0.10/out/file-controller.js
- /Users/virgil/.vscode/extensions/seelog.python-init-generator-0.0.10/out/extension.js
...
```
And actually, the `node_modules` folder inside `.vscode/extensions/seelog...` is missing. 

I have tried the extension on another machine and have the same issue.

**Comment by SeeLog** [comment]
@sisoe24 Thank you for reporting this issue.

Maybe same as #1.

Now, I updated some packages and then uploaded the new extension(v0.0.12).
I reinstall the extension from the market, then I confirm it works.

Oddly, sometimes node_modules dir disappears on this project.
This time, I solved this issue by updating packages, but maybe it will occur in the future.

If you couldn't confirm v0.0.12 works, please re-open this issue.
